version: "3.8"

services:
  api:
    container_name: "quickdoc_api"
    image: node
    volumes:
      - ./api:/usr/src/api
    ports:
      - "${API_PORT}:3001"
    links:
      - "database"
    env_file:
      - .env
    command: "/bin/bash -c 'cd /usr/src/api && npm install && npm run ${NODE_ENV}'"
    working_dir: /usr/src/api

  database:
    container_name: "quickdoc_database"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - ./dbdata:/data/db
volumes:
  dbdata:
    driver: local
